#pragma kernel CSMain
[numthreads(10, 1, 1)]
struct Sphere {
	float3 direction;
	float3 position;
	float3 color;
	float weight;
	float radius;
	float speed;
};

float floor;
float height;
float tf;
float delta = 0;

RWStructuredBuffer<Sphere> objs;

float rand(float2 co) {
	return (frac(sin(dot(co.xy, float2(12.9898, 78233))) * 43758.5453)) * 1;
}
void CSMain(uint3 id : SV_DispatchThreadID)
{
	
}
